# Generated by Django 5.1.4 on 2025-01-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_role_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passenger',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
