# Generated by Django 5.1.4 on 2025-03-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='free_places',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
