# Generated by Django 5.1.4 on 2025-02-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_trip_id', models.CharField(help_text='Идентификатор рейса, полученный из приложения CRM', max_length=255)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('baggage_option', models.CharField(blank=True, help_text='Опционально: выбор багажа (например, маленький, средний, большой)', max_length=50, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
