# Generated by Django 5.1.4 on 2025-02-24 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='crm_trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='crm.trip'),
        ),
    ]
