# Generated by Django 5.1.4 on 2025-03-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_reservation_crm_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='free_places',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
