# Generated by Django 5.1.4 on 2025-03-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_reservation_free_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='free_places',
        ),
    ]
